server:
  port: 8095
spring:
  data:
    mongodb:
      uri: mongodb+srv://Omprakash:Prakash1997@cluster0.psdii.mongodb.net/Ratings-Reviews?retryWrites=true&w=majority
  application:
    name: RATINGS-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761
  instance:
    hostname: localhost